const list = [{
        _id: "1",
        name: "ACCORDING DRESS",
        category: "dress",
        image: "../../public/images/girls//dress/swiss.jpg",
        price: "600",
        amount: 0,
        description: "Care for fiber & water: at least 25% recycled polyester. We use the Join Life label on clothing that is produced using technology and raw materials that help us to reduce the environmental impact of our products. ",
    },
    /*    {
            _id: "2",
            name: "KNITTED DRESS",
            category: "dress",
            image: "../public//images/girls/dress/smoked.jpg",
            price: 800,
            amount: 0,
            description: "Care for fiber & water: at least 25% recycled polyester. We use the Join Life label on clothing that is produced using technology and raw materials that help us to reduce the environmental impact of our products. ",
        },
        {
            _id: "3",
            name: "DRESS WITH DAISY",
            image: "../public//images/girls/dress/daisy.jpg",
            price: 1250,
            amount: 0,
            category: "dress",
            description: "Care for fiber & water: at least 25% recycled polyester. We use the Join Life label on clothing that is produced using technology and raw materials that help us to reduce the environmental impact of our products. ",
        },

        {
            _id: "7",
            name: "Quilted jacket",
            category: "jacket",
            image: "../public//images/girls/jackets/quilt-bomber.jpg",
            price: "2600",
            description: "Care for fiber & water: at least 25% recycled polyester. We use the Join Life label on clothing that is produced using technology and raw materials that help us to reduce the environmental impact of our products. ",
        },
        {
            _id: "8",
            name: "RAINCOAT",
            category: "jacket",
            image: "../public//images/girls/jackets/raincoat.jpg",
            price: 3800,
            description: "Care for fiber & water: at least 25% recycled polyester. We use the Join Life label on clothing that is produced using technology and raw materials that help us to reduce the environmental impact of our products. ",
        },
        {
            _id: "9",
            name: "T-shirt  firls girls",
            category: "tshirt",
            image: "../public//images/girls/category/t-shirt.jpg",
            price: 3800,
            description: "Care for fiber & water: at least 25% recycled polyester. We use the Join Life label on clothing that is produced using technology and raw materials that help us to reduce the environmental impact of our products. ",
        },
        {
            _id: "10",
            name: "T-shirt for boys",
            category: "tshirt",
            image: "../public//images/boys/t-shirt/t-1.jpg",
            price: 900,
            description: "Care for fiber & water: at least 25% recycled polyester. We use the Join Life label on clothing that is produced using technology and raw materials that help us to reduce the environmental impact of our products. ",
        },

        {
            _id: "11",
            name: "Sport ",
            category: "sport",
            image: "../public//images/boys/sport/s-1.jpg",
            price: 1700,
            description: "Care for fiber & water: at least 25% recycled polyester. We use the Join Life label on clothing that is produced using technology and raw materials that help us to reduce the environmental impact of our products. ",
        },
        {
            _id: "12",
            name: "Sport Girl ",
            category: "sport",
            image: "../public//images/girls/category/sport.jpg",
            price: 2800,
            description: "Care for fiber & water: at least 25% recycled polyester. We use the Join Life label on clothing that is produced using technology and raw materials that help us to reduce the environmental impact of our products. ",
        }, */
];
export default list;